version: '3'

services:

  app:
    image: quay.io/keycloak/keycloak:21.1
    command: 
      - start-dev
      - -Dkeycloak.profile.feature.upload_scripts=enabled
    container_name: micro-auth-app
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://db:3306/client_auth
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
      - KC_IMPORT=/tmp/realm-export.json
    ports:
      - 8080:8080
    volumes: 
      - ./themes/slack:/opt/jboss/keycloak/themes/slack
      - ./realm-export.json:/tmp/realm-export.json
    depends_on: 
      db:
        condition: service_healthy
    networks:
      - xpto

  db:
    image: mysql:8.0.30-debian
    container_name: micro-auth-db
    restart: always
    tty: true
    # ports:
    #   - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=client_auth
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - xpto

networks:
  xpto:
    external: true

# http://localhost:8080
# http://host.docker.internal:8080

### Windows      
# - C:\Windows\system32\drivers\etc\hosts

### Mac e Linux
# - /etc/hosts

# 127.0.0.1 host.docker.internal